export const infoWrap: string;
export const label: string;
export const labelWrap: string;
export const pictureWrap: string;
export const root: string;
export const statItem: string;
export const statValue: string;
export const statWrap: string;
export const titleName: string;
