// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button--large': string;
  'button--medium': string;
  'button--small': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
